/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  TaskCreate,
  TaskCreateResponse,
  TaskResponse,
  TaskUpdate,
  WorkspaceStatusResponse
} from '../fastAPI.schemas';




  export const getTask = () => {
/**
 * @summary Create Task
 */
const createTaskApiTaskPost = <TData = AxiosResponse<TaskCreateResponse>>(
    taskCreate: TaskCreate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/task/`,
      taskCreate,options
    );
  }
/**
 * @summary Update Task
 */
const updateTaskApiTaskTaskIdPut = <TData = AxiosResponse<TaskCreateResponse>>(
    taskId: string,
    taskUpdate: TaskUpdate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/task/${taskId}`,
      taskUpdate,options
    );
  }
/**
 * @summary Get Task
 */
const getTaskApiTaskTaskIdGet = <TData = AxiosResponse<TaskResponse>>(
    taskId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/task/${taskId}`,options
    );
  }
/**
 * @summary Get Task Status
 */
const getTaskStatusApiTaskTaskIdStatusGet = <TData = AxiosResponse<WorkspaceStatusResponse>>(
    taskId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/task/${taskId}/status`,options
    );
  }
return {createTaskApiTaskPost,updateTaskApiTaskTaskIdPut,getTaskApiTaskTaskIdGet,getTaskStatusApiTaskTaskIdStatusGet}};
export type CreateTaskApiTaskPostResult = AxiosResponse<TaskCreateResponse>
export type UpdateTaskApiTaskTaskIdPutResult = AxiosResponse<TaskCreateResponse>
export type GetTaskApiTaskTaskIdGetResult = AxiosResponse<TaskResponse>
export type GetTaskStatusApiTaskTaskIdStatusGetResult = AxiosResponse<WorkspaceStatusResponse>
