/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  LoginRequest,
  TokenResponse,
  UserCreate,
  UserResponse
} from '../fastAPI.schemas';




  export const getAuth = () => {
/**
 * @summary Register User
 */
const registerUserApiAuthRegisterPost = <TData = AxiosResponse<UserResponse>>(
    userCreate: UserCreate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/auth/register`,
      userCreate,options
    );
  }
/**
 * @summary Login
 */
const loginApiAuthLoginPost = <TData = AxiosResponse<TokenResponse>>(
    loginRequest: LoginRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/auth/login`,
      loginRequest,options
    );
  }
return {registerUserApiAuthRegisterPost,loginApiAuthLoginPost}};
export type RegisterUserApiAuthRegisterPostResult = AxiosResponse<UserResponse>
export type LoginApiAuthLoginPostResult = AxiosResponse<TokenResponse>
