"""added cascade delete

Revision ID: 006b4a449843
Revises: 2646599f0e3d
Create Date: 2025-04-26 21:25:01.920468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '006b4a449843'
down_revision: Union[str, None] = '2646599f0e3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('notification_taskId_fkey', 'notification', type_='foreignkey')
    op.create_foreign_key(None, 'notification', 'task', ['taskId'], ['id'], ondelete='CASCADE')
    op.drop_constraint('task_workspaceId_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'workspace', ['workspaceId'], ['id'], ondelete='CASCADE')
    op.drop_constraint('workspace_ownerId_fkey', 'workspace', type_='foreignkey')
    op.create_foreign_key(None, 'workspace', 'user', ['ownerId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspace', type_='foreignkey')
    op.create_foreign_key('workspace_ownerId_fkey', 'workspace', 'user', ['ownerId'], ['id'])
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_workspaceId_fkey', 'task', 'workspace', ['workspaceId'], ['id'])
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.create_foreign_key('notification_taskId_fkey', 'notification', 'task', ['taskId'], ['id'])
    # ### end Alembic commands ###
