"""add_task_status_notification

Revision ID: 2646599f0e3d
Revises: 969f5d216414
Create Date: 2025-04-26 17:03:42.668899

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2646599f0e3d'
down_revision: Union[str, None] = '969f5d216414'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaceTaskStatus',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.VARCHAR(length=225), nullable=False),
                    sa.Column('workspaceId', sa.UUID(), nullable=True),
                    sa.ForeignKeyConstraint(['workspaceId'], ['workspace.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('task',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('title', sa.VARCHAR(length=225), nullable=False),
                    sa.Column('description', sa.TEXT(), nullable=True),
                    sa.Column('dueDate', postgresql.TIMESTAMP(), nullable=True),
                    sa.Column('workspaceId', sa.UUID(), nullable=True),
                    sa.Column('statusId', sa.UUID(), nullable=True),
                    sa.ForeignKeyConstraint(['statusId'], ['workspaceTaskStatus.id'], ),
                    sa.ForeignKeyConstraint(['workspaceId'], ['workspace.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('notification',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('message', sa.TEXT(), nullable=False),
                    sa.Column('eventType',
                              postgresql.ENUM('TASK_CREATED', 'TASK_UPDATED', 'TASK_ASSIGNED', 'TASK_UNASSIGNED',
                                              'TASK_DELETED', 'TASK_STATUS_CHANGED', 'TASK_DUE_SOON', 'TASK_COMPLETED',
                                              name='eventtypeenum'), nullable=False),
                    sa.Column('createdAt', postgresql.TIMESTAMP(), nullable=True),
                    sa.Column('taskId', sa.UUID(), nullable=True),
                    sa.ForeignKeyConstraint(['taskId'], ['task.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    op.drop_table('task')
    op.drop_table('workspaceTaskStatus')
    # ### end Alembic commands ###
