"""added workspace user join table

Revision ID: 3008a016b0df
Revises: 303e25f93a5e
Create Date: 2025-05-18 15:43:10.879437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3008a016b0df'
down_revision: Union[str, None] = '303e25f93a5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_user',
    sa.Column('workspaceId', sa.UUID(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workspaceId'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('workspaceId', 'userId')
    )
    op.drop_constraint('workspace_ownerId_fkey', 'workspace', type_='foreignkey')
    op.drop_column('workspace', 'ownerId')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace', sa.Column('ownerId', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('workspace_ownerId_fkey', 'workspace', 'user', ['ownerId'], ['id'], ondelete='CASCADE')
    op.drop_table('workspace_user')
    # ### end Alembic commands ###
