"""added cascade delete on assignee_task

Revision ID: 604d837507e7
Revises: 3008a016b0df
Create Date: 2025-05-26 22:11:16.567219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '604d837507e7'
down_revision: Union[str, None] = '3008a016b0df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('assignee_task_taskId_fkey', 'assignee_task', type_='foreignkey')
    op.create_foreign_key(None, 'assignee_task', 'task', ['taskId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assignee_task', type_='foreignkey')
    op.create_foreign_key('assignee_task_taskId_fkey', 'assignee_task', 'task', ['taskId'], ['id'])
    # ### end Alembic commands ###
