"""update event type enum

Revision ID: 864711cbeb93
Revises: 040c97787f1b
Create Date: 2025-05-29 16:38:43.211889

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '864711cbeb93'
down_revision: Union[str, None] = '040c97787f1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

new_values = [
    'TASK_DUE_DATE_CHANGED',
    'TASK_DESCRIPTION_CHANGED',
    'TASK_TITLE_CHANGED'
]


def upgrade() -> None:
    """Upgrade schema."""
    for value in new_values:
        op.execute(f"ALTER TYPE eventtypeenum ADD VALUE IF NOT EXISTS '{value}';")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
