"""added cascade delete to workspace task status

Revision ID: 9258b4fc83de
Revises: 006b4a449843
Create Date: 2025-04-26 21:27:04.652213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9258b4fc83de'
down_revision: Union[str, None] = '006b4a449843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('workspaceTaskStatus_workspaceId_fkey', 'workspaceTaskStatus', type_='foreignkey')
    op.create_foreign_key(None, 'workspaceTaskStatus', 'workspace', ['workspaceId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaceTaskStatus', type_='foreignkey')
    op.create_foreign_key('workspaceTaskStatus_workspaceId_fkey', 'workspaceTaskStatus', 'workspace', ['workspaceId'], ['id'])
    # ### end Alembic commands ###
