"""add user_workspace

Revision ID: 969f5d216414
Revises: 
Create Date: 2025-03-18 21:46:19.782341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '969f5d216414'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=320), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('passwordHash', sa.VARCHAR(), nullable=False),
    sa.Column('fullName', sa.VARCHAR(length=225), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('workspace',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=225), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'PLANNING', 'ON_HOLD', 'COMPLETED', name='workspacestatusenum'), nullable=False),
    sa.Column('ownerId', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['ownerId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workspace')
    op.drop_table('user')
    # ### end Alembic commands ###
