"""added creator id to notification

Revision ID: bb3b92d21d24
Revises: eb31b344d534
Create Date: 2025-05-28 00:32:35.538830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb3b92d21d24'
down_revision: Union[str, None] = 'eb31b344d534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('creatorId', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'notification', 'user', ['creatorId'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_column('notification', 'creatorId')
    # ### end Alembic commands ###
