"""added cascade delete on recipient_notification

Revision ID: eb31b344d534
Revises: 604d837507e7
Create Date: 2025-05-26 22:16:50.316824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb31b344d534'
down_revision: Union[str, None] = '604d837507e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recipient_notification_notificationId_fkey', 'recipient_notification', type_='foreignkey')
    op.create_foreign_key(None, 'recipient_notification', 'notification', ['notificationId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipient_notification', type_='foreignkey')
    op.create_foreign_key('recipient_notification_notificationId_fkey', 'recipient_notification', 'notification', ['notificationId'], ['id'])
    # ### end Alembic commands ###
