/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  UserNotificationResponse,
  UserResponse,
  UserUpdate
} from '../fastAPI.schemas';




  export const getUser = () => {
/**
 * @summary Get Users
 */
const getUsersApiUserAllGet = <TData = AxiosResponse<UserResponse[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/user/all`,options
    );
  }
/**
 * @summary Get User
 */
const getUserApiUserUserIdGet = <TData = AxiosResponse<UserResponse>>(
    userId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/user/${userId}`,options
    );
  }
/**
 * @summary Update User
 */
const updateUserApiUserUserIdPut = <TData = AxiosResponse<UserResponse>>(
    userId: string,
    userUpdate: UserUpdate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/user/${userId}`,
      userUpdate,options
    );
  }
/**
 * @summary Delete User
 */
const deleteUserApiUserUserIdDelete = <TData = AxiosResponse<UserResponse>>(
    userId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/api/user/${userId}`,options
    );
  }
/**
 * @summary Get User Notifications
 */
const getUserNotificationsApiUserUserIdNotificationsGet = <TData = AxiosResponse<UserNotificationResponse[]>>(
    userId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/user/${userId}/notifications`,options
    );
  }
return {getUsersApiUserAllGet,getUserApiUserUserIdGet,updateUserApiUserUserIdPut,deleteUserApiUserUserIdDelete,getUserNotificationsApiUserUserIdNotificationsGet}};
export type GetUsersApiUserAllGetResult = AxiosResponse<UserResponse[]>
export type GetUserApiUserUserIdGetResult = AxiosResponse<UserResponse>
export type UpdateUserApiUserUserIdPutResult = AxiosResponse<UserResponse>
export type DeleteUserApiUserUserIdDeleteResult = AxiosResponse<UserResponse>
export type GetUserNotificationsApiUserUserIdNotificationsGetResult = AxiosResponse<UserNotificationResponse[]>
